IDIR=./annotated
EDIR=./annotated-working
CLANG_FLAGS += -I ../xdcc_echo -I ../../../amqlib
CONSTRAINTS=$(CLOSURE_PYTHON)/conflict_analyzer/constraints

topology:
	conflict_analyzer \
	--pdg-lib $(CLOSURE_LIBS)/libpdg.so \
	--constraint-files \
		$(CONSTRAINTS)/conflict_variable_declarations.mzn \
		$(CONSTRAINTS)/conflict_analyzer_constraints.mzn \
	--output topology.json \
	--source-path $(realpath .)/refactored \
	annotated/example1.c 

