#!/usr/bin/python3
#-*- coding: utf-8 -*-
import re
import sys
from gedl import RPC_shubh1
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(RPC_shubh1.main())